"""Grundmodell: bundles und karten

Revision ID: ccc906f048c0
Revises: 
Create Date: 2026-08-27 16:20:28.026137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccc906f048c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('titel', sa.Text(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('klasse', sa.String(length=60), nullable=True),
    sa.Column('selbsteinschaetzung', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('reihenfolge', sa.String(length=20), server_default='zufall', nullable=False),
    sa.Column('aktiv', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reihenfolge IN ('zufall', 'fest')", name='ck_bundles_reihenfolge'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('karten',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bundle_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('art', sa.String(length=12), nullable=False),
    sa.Column('vorderseite', sa.Text(), nullable=False),
    sa.Column('rueckseite', sa.Text(), nullable=True),
    sa.Column('antworten', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('richtige_index', sa.Integer(), nullable=True),
    sa.Column('erklaerung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (art = 'flashcard'\n                AND rueckseite IS NOT NULL\n                AND antworten IS NULL\n                AND richtige_index IS NULL\n                AND erklaerung IS NULL)\n            OR\n            (art = 'frage'\n                AND rueckseite IS NULL\n                AND antworten IS NOT NULL\n                AND richtige_index IS NOT NULL)\n            ", name='ck_karten_felder_passen_zur_art'),
    sa.CheckConstraint("\n            art <> 'frage'\n            OR (jsonb_typeof(antworten) = 'array'\n                AND jsonb_array_length(antworten) BETWEEN 2 AND 4)\n            ", name='ck_karten_antwortanzahl'),
    sa.CheckConstraint("\n            art <> 'frage'\n            OR (richtige_index >= 0\n                AND richtige_index < jsonb_array_length(antworten))\n            ", name='ck_karten_richtige_index_im_bereich'),
    sa.CheckConstraint("art IN ('flashcard', 'frage')", name='ck_karten_art'),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bundle_id', 'position', deferrable=True, initially='DEFERRED', name='uq_karten_bundle_position')
    )
    op.create_index(op.f('ix_karten_bundle_id'), 'karten', ['bundle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_karten_bundle_id'), table_name='karten')
    op.drop_table('karten')
    op.drop_table('bundles')
    # ### end Alembic commands ###
