"""oauth-tabellen

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-27 23:57:17.975983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_clients',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=True),
    sa.Column('redirect_uris', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scope', sa.String(length=120), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            CASE\n                WHEN jsonb_typeof(redirect_uris) = \'array\'\n                    THEN jsonb_array_length(redirect_uris) >= 1\n                        AND jsonb_array_length(redirect_uris) = jsonb_array_length(\n                            jsonb_path_query_array(\n                                redirect_uris, \'strict $[*] ? (@.type() == "string")\'))\n                ELSE false\n            END\n            ', name='ck_oauth_clients_redirect_uris'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('oauth_codes',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('code_challenge', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=120), nullable=False),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.Column('familie_id', sa.UUID(), nullable=False),
    sa.Column('ablauf_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eingeloest_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(redirect_uri) <= 2000', name='ck_oauth_codes_redirect_uri_max_laenge'),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code_hash')
    )
    op.create_table('oauth_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('art', sa.String(length=30), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('familie_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=120), nullable=False),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.Column('ablauf_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('zurueckgezogen_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("art IN ('zugriff', 'erneuerung')", name='ck_oauth_tokens_art'),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_oauth_tokens_familie_id'), 'oauth_tokens', ['familie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_tokens_familie_id'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_table('oauth_codes')
    op.drop_table('oauth_clients')
    # ### end Alembic commands ###
